@startuml
start

:Enter Expense Splitter;

if () then ([receiptIsNotDone])

    if () then ([notDoneAddingItems])
    : Visit SimplifiedAddItemActivityDiagram
     below this diagram;
    : DoneReceipt;

    else ([finishedAddingItems])
    : Done Receipt;
    endif


else ([receiptIsDone])

endif


: Paid Command;

: Clear Receipt;




stop
@enduml
